# Generated by Django 4.1.7 on 2023-02-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='Qisqacha')),
                ('body', models.TextField(verbose_name='Tekst')),
                ('photo', models.ImageField(blank=True, upload_to='images/', verbose_name='Foto')),
                ('result', models.IntegerField(default=0, verbose_name='Natija')),
                ('dcreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tashabbus',
                'verbose_name_plural': 'Tashabbuslar',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(max_length=200, verbose_name='Taklif')),
                ('offer_result', models.TextField(verbose_name='Taklif natijalari')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='initiatives.initiative')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
            },
        ),
    ]
