# Generated by Django 4.1.7 on 2023-02-23 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_alter_offer_offer_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, verbose_name='Taklif')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='initiatives.initiative')),
            ],
        ),
    ]
