# Generated by Django 4.1.7 on 2023-02-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Izoh', 'verbose_name_plural': 'Izohlar'},
        ),
        migrations.AddField(
            model_name='comment',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fio',
            field=models.CharField(blank=True, max_length=200, verbose_name='fio'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='Izoh'),
        ),
    ]
