# Generated by Django 4.1.7 on 2023-02-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0004_alter_comment_options_comment_draft_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
    ]
