# Generated by Django 4.1.7 on 2023-03-02 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('initiatives', '0005_alter_comment_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='likes',
            field=models.ManyToManyField(related_name='initiative_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
